### ISSUE TITLE
[ERROR TEMPLATE] Java - java.util.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nedpals** [nedpals/errgoengine#23]
| Name | Type | Code | Language |
|--|--|--|--|
|java.util.StringIndexOutOfBoundsException|Runtime Exception|java.util.StringIndexOutOfBoundsException|Java|

## Description
An attempt to access a string's index that is out of its range.

## Sample Code
```
public class Main {
    public static void main(String[] args) {
        String text = "Hello, World!";
        // Attempting to access an index beyond the string's length
        char character = text.charAt(20);
        System.out.println(character);
    }
}
```
## Sample Error Message
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 20
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at Main.main(Main.java:5)
```

## Implementation Checklist
- [x] Implemented analysis
- [x] Implemented explanation translation
- [x] Implemented bug fix generation
- [x] Add tests

**Comment by nedpals** [comment]
Might be applicable with #8
