### ISSUE TITLE
[ERROR TEMPLATE] Java - ArithmeticException

### ISSUE THREAD

**Issue by nedpals** [nedpals/errgoengine#28]
| Name | Type | Code | Language |
|--|--|--|--|
|ArithmeticException|Runtime Exception|java.lang.ArithmeticException|Java|

## Description
Generic arithmetic error, like division by zero or an overflow.

## Sample Code
```java
public class Arith {
	public static void main(String[] args) {
		double out = 3 / 0;
		System.out.println(out);
	}
}
```
## Sample Error Message
```
Exception in thread "main" java.lang.ArithmeticException: / by zero
    at Arith.main(Arith.java:3)
```

## Implementation Checklist
- [x] Implemented analysis
- [x] Implemented explanation translation
- [x] Implemented bug fix generation
- [x] Add tests

**Comment by nedpals** [comment]
| Name | Type | Code | Language |
|--|--|--|--|
|ArithmeticException|Runtime Exception|java.lang.ArithmeticException|Java|

## Description
Occurs when the result of a division is recurring (never ending), and we haven't specified rounding mode/scale. In other words, BigDecimal won't know how to represent a recurring division result if we haven't specified to what decimal places the result should be rounded, so it throws this exception.

https://www.logicbig.com/how-to/code-snippets/jcode-java-exception-arithmeticexception-no-exact-representable-error.html

## Sample Code
```java
import java.math.BigDecimal;

public class ArithEx {
    public static void main(String[] args) {
        BigDecimal a = new BigDecimal(5);
        BigDecimal b = new BigDecimal(3);
        BigDecimal result = a.divide(b);
        System.out.println(result);
    }
}

```
## Sample Error Message
```
Exception in thread "main" java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
        at java.base/java.math.BigDecimal.divide(BigDecimal.java:1722)
        at ArithEx.main(ArithEx.java:7)
```

## Implementation Checklist
- [ ] Implemented analysis
- [ ] Implemented explanation translation
- [ ] Implemented bug fix generation
- [x] Add tests

**Comment by nedpals** [comment]
UPDATE: Lacking `BigInt` stub support
